@startuml

class 保証人
class クラブ
class 学校種
class 入寮者
class 建物
class フロア
class 部屋
class 住所
class 契約
class 誓約
class 口座
class 寮管理者
class 入金
class 学籍 {
    入学年度
    受験番号
}
class 入退去

学籍 -- 大学生

入金 <|-- 全納
入金 <|-- 分納
入金 <|-- 月払

寮管理者 -- 入寮者: 部屋割当
寮管理者 -- 入寮者: 減免する
寮管理者 -- 入寮者: 退寮の申請
寮管理者 -- 入寮者: 鍵引き渡す
寮管理者 -- 入寮者: 請求する
入寮者 <|-- 大学生
入寮者 <|-- 高校生
入寮者 <|-- 社会人
建物 -- 入退去
入退去 -- 入寮者
部屋 -- 契約
契約 -- 入寮者
部屋 -- 誓約
誓約 -- 入寮者
入寮者 -- 入金
入金 -- 口座
建物 o- フロア
フロア o- 部屋
学校種 -- クラブ
大学生 -- 学校種: 所属する
高校生 -- 学校種: 所属する
入寮者 -- クラブ: 所属する
入寮者 -- 保証人: 保証する

@enduml