@startuml
package Shared {
  class TimePeriod {
    startedAt
    endedAt
  }
}
package RentalProperty{
  class Building
  class Floor
  class Room
  Building o- Floor
  Floor o- Room
  Building -- Location.Address
}
package Rent {
  class Contract
  class Pledge
  class Guaranty {
    guarantor
    guarantee
  }
  note top of Guaranty: 保証人になれるのは社会人のみ
  note top of Guaranty: 学生は保証人必須
  class Application
  class MoveInOut {
    moveInAt
  }
  class HandOverKey
  class RoomAssignment
  Room -- Contract
  Contract -- Resident.RentParty
  Room -- Pledge
  Pledge -- Resident.RentParty
  Room -- MoveInOut
  MoveInOut -- Resident.RentParty
  Room -- HandOverKey
  HandOverKey -- Resident.RentParty
  Room -- RoomAssignment
  RoomAssignment -- Resident.RentParty
  Application -- Resident.RentParty
  Guaranty -- Resident.RentParty:被保証
  Guaranty -- Resident.Individual: 保証人
}
package Resident{
  class RentParty
  class LocationParty
  class Corporation
  class Individual

  RentParty --> Individual
  RentParty --> Corporation
  LocationParty --> Individual
  LocationParty --> Corporation
  LocationParty -- Location.Email
  LocationParty -- Location.Address
  LocationParty -- Location.Phone
  Individual - Corporation :勤務
}
package Location{
  class Address
  class Phone
  class Email
}

package Payment {
  class BankAccount {
    BankCode
    BankBranchCode
    AccountType
    AccountNumber
    AccountName
    AccountNameKana
  }
  class Payment
  class PaymentTerm
  class Exemption
  class FullPayment
  class Installment
  Payment --- Contract
  Exemption -- Contract
  Payment <|-- FullPayment
  Payment <|-- Installment
}

package school {
  class SchoolRegister {
    startedAt
    examNumber
  }
  class OrganizationStructure
  class Organization
  class School
  class Faculty
  class Department
  class Club {
    string name
  }
  Organization <|-- School
  Organization <|-- Faculty
  Organization <|-- Department
  OrganizationStructure "*" -right- "1" Organization :親
  OrganizationStructure "*" -right- "1" Organization :子
  OrganizationStructure "*" -down- "1" TimePeriod
  Resident.Individual -- SchoolRegister
  SchoolRegister - Organization
  Club -- SchoolRegister :belongs
}

@enduml